<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2021 Combod SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here
	'Class:MailInboxO365' => 'Office 365 Mailbox',
	'Class:MailInboxO365+' => 'Configuration for reading eMails from an Office 365 Mailbox',
	'Class:MailInboxO365/Attribute:azure_authorization' => 'Authorization Status',
	'Class:MailInboxO365/Attribute:azure_client_id' => 'Application (client) ID',
	'Class:MailInboxO365/Attribute:azure_client_id+' => 'Application ID of the Azure AD registered application',
	'Class:MailInboxO365/Attribute:azure_tenant_id' => 'Directory (tenant) ID',
	'Class:MailInboxO365/Attribute:azure_tenant_id+' => 'Directory ID of the Azure AD registered application',
	'Class:MailInboxO365/Attribute:azure_secret' => 'Client Secret',
	'Class:MailInboxO365/Attribute:azure_secret+' => 'Client Secret generated by Azure AD',
	'itop-o365-email-synchro/Operation:DisplayConfiguration/Title' => 'Azure AD Configuration for Office 365',
	'O365:AzureAuthorization:Ok' => 'Ok',
	'O365:AzureAuthorization:KO' => 'Not Authorized',
	'O365:AzureAuthorization:ClickToInit' => '%1$s Click <a href="%2$s">here</a> to complete the authorization process',
	'O365:AzureAuthorization:ClickToRenew' => '%1$s Click <a href="%2$s">here</a> to renew the authorization process',
	'O365:AzureAuthorization:ClickForMoreInfo' => 'Click <a href="%1$s" target="_blank">here</a> for information about the required Azure configuration',
));
