<?php
/**
 * Localized data
 *
 * @copyright   Copyright (C) 2013 XXXXX
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

Dict::Add('EN US', 'English', 'English', array(
	// Dictionary entries go here
	'Class:MailInboxO365' => 'Office 365 Mailbox',
	'Class:MailInboxO365+' => 'Configuration for reading eMails from an Office 365 Mailbox',
	'Class:MailInboxO365/Attribute:azure_authorization' => 'Authorization Status',
	'Class:MailInboxO365/Attribute:azure_client_id' => 'Application (client) ID',
	'Class:MailInboxO365/Attribute:azure_client_id+' => 'Application ID of the Azure AD registered application',
	'Class:MailInboxO365/Attribute:azure_tenant_id' => 'Directory (tenant) ID',
	'Class:MailInboxO365/Attribute:azure_tenant_id+' => 'Directory ID of the Azure AD registered application',
	'Class:MailInboxO365/Attribute:azure_secret' => 'Client Secret',
	'Class:MailInboxO365/Attribute:azure_secret+' => 'Client Secret generated by Azure AD',
	'itop-o365-email-synchro/Operation:DisplayConfiguration/Title' => 'Azure AD Configuration for Office 365',
));
