<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'itop-o365-email-synchro/0.0.1',
	array(
		// Identification
		//
		'label' => 'Office 365 eMail Synchro',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-standard-email-synchro/3.1.3'
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'vendor/autoload.php',
			'model.itop-o365-email-synchro.php', // Contains the PHP code generated by the "compilation" of datamodel.itop-o365-email-synchro.xml
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);


?>
